= Tester les APIs web avec Karaté

== Introduction

`Karate` est un framework open-source pour tester ses API web.

Véritable boite à outils pour écrire simplement des tests de services web avec son DSL proche de la syntaxe `Gherkin`.

Tour d'horizon de cet outil indispensable !


=== DSL Karaté

* framework orienté web
* basé sur le langage Gherkin
* sémantique `Given When Then`

== Premiers pas / démarrage

Karate peut s'exécuter en standalone, avec un build maven ou avec un build graddle.

.Ecriture d'un fichier feature
[]
----
Feature: recuperation simple d'un produit

  Scenario: recupere la liste des produits
    Given url "http://localhost:9090/Produits"
    When method get
    Then status 200
    And match response[0] ==
    """
    {"id":'#notnull',"nom":"Ordinateur portable","prix":350,"prixAchat":120}
    """

----


il faut récupérer le jar du karate en standalone.


.Lancement en standalone
[]
----
cd premier-pas-karate
java -jar karate.jar 1_recup-produit-simple.feature
----

.Résultat exécution
[]
----
15:13:42.492 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - request:
1 > GET http://localhost:9090/Produits
1 > Accept-Encoding: gzip,deflate
1 > Connection: Keep-Alive
1 > Host: localhost:9090
1 > User-Agent: Apache-HttpClient/4.5.11 (Java/14)

15:13:42.516 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - response time in milliseconds: 22,36
1 < 200
1 < Content-Type: application/json;charset=UTF-8
1 < Date: Thu, 23 Jul 2020 13:13:42 GMT
1 < Transfer-Encoding: chunked
[{"id":1,"nom":"Ordinateur portable","prix":350,"prixAchat":120},{"id":2,"nom":"Aspirateur Robot","prix":500,"prixAchat":200},{"id":3,"nom":"Table de Ping Pong","prix":750,"prixAchat":400},{"id":4,"nom":"test","prix":100,"prixAchat":120},{"id":5,"nom":"test","prix":100,"prixAchat":120},{"id":6,"nom":"test","prix":100,"prixAchat":120},{"id":7,"nom":"test","prix":100,"prixAchat":120},{"id":8,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":9,"nom":"test","prix":100,"prixAchat":120},{"id":10,"nom":"test","prix":100,"prixAchat":120},{"id":11,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":12,"nom":"test","prix":100,"prixAchat":120},{"id":13,"nom":"test","prix":100,"prixAchat":120},{"id":14,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":15,"nom":"test","prix":100,"prixAchat":120},{"id":16,"nom":"test","prix":100,"prixAchat":120},{"id":17,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":18,"nom":"test","prix":100,"prixAchat":120},{"id":19,"nom":"test","prix":100,"prixAchat":120},{"id":20,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":21,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":22,"nom":"test","prix":100,"prixAchat":120},{"id":23,"nom":"test","prix":100,"prixAchat":120},{"id":24,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":25,"nom":"test","prix":100,"prixAchat":120},{"id":26,"nom":"test","prix":100,"prixAchat":120},{"id":27,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":28,"nom":"test","prix":100,"prixAchat":120},{"id":29,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":30,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":31,"nom":"test","prix":100,"prixAchat":120},{"id":32,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":33,"nom":"test","prix":100,"prixAchat":120},{"id":34,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":35,"nom":"test","prix":100,"prixAchat":120},{"id":36,"nom":"test","prix":100,"prixAchat":120},{"id":37,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":38,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":39,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":40,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":41,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":42,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":43,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":44,"nom":"test","prix":100,"prixAchat":120},{"id":45,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":46,"nom":"test","prix":100,"prixAchat":120},{"id":47,"nom":"mon Produit","prix":10,"prixAchat":100},{"id":48,"nom":"test","prix":100,"prixAchat":120},{"id":49,"nom":"test","prix":100,"prixAchat":120}]


HTML report: (paste into browser to view) | Karate version: 0.9.5
file:/Users/jbcotard/Documents/work/2020_karate/demo-karate/tests-karate/target/surefire-reports/src.test.java.examples.produits.1_recup-produit-simple.html
---------------------------------------------------------

15:13:42.626 [pool-1-thread-1] INFO  com.intuit.karate.Runner - <<pass>> feature 1 of 1: src/test/java/examples/produits/1_recup-produit-simple.feature
---------------------------------------------------------
feature: src/test/java/examples/produits/1_recup-produit-simple.feature
report: target/surefire-reports/src.test.java.examples.produits.1_recup-produit-simple.json
scenarios:  1 | passed:  1 | failed:  0 | time: 0,2970
---------------------------------------------------------
Karate version: 0.9.5
======================================================
elapsed:   0,91 | threads:    1 | thread time: 0,30
features:     1 | ignored:    0 | efficiency: 0,33
scenarios:    1 | passed:     1 | failed: 0
======================================================

----

== d'autres exemples

dans Intellij,

petit focus sur l'utilisation Karate dans Intellij

utilisation du plugin "Cucumber pour java"

== exemple de scénario avec enchainement de requetes

Maintenant imaginons que pour tester une fonctionnalité, il faut enchainer les appels de plusieurs API.


.Ecriture du fichier feature
[]
----
Feature: recuperation d'un produit

  Background:
    * url baseUrl

  Scenario: recupere un produit par son id

    * def produit =
      """
      {
        "nom": "mon Produit",
        "prix": 10,
        "prixAchat": 100
      }
      """
    Given path 'Produits'
    And request produit
    And header Content-Type = 'application/json'
    When method post
    Then status 201
    And match responseHeaders contains { Location: '#notnull' }

    * def locationProduit = responseHeaders['Location'][0]
    * print 'url produit : ', locationProduit

    Given url locationProduit
    When method get
    Then status 200
    And assert response.nom == produit.nom

----

.Résultat exécution test
[]
----
15:19:07.330 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - request:
1 > POST http://localhost:9090/Produits
1 > Accept-Encoding: gzip,deflate
1 > Connection: Keep-Alive
1 > Content-Length: 47
1 > Content-Type: application/json; charset=UTF-8
1 > Host: localhost:9090
1 > User-Agent: Apache-HttpClient/4.5.11 (Java/14)
{"nom":"mon Produit","prix":10,"prixAchat":100}

15:19:07.349 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - response time in milliseconds: 17,84
1 < 201
1 < Content-Length: 0
1 < Date: Thu, 23 Jul 2020 13:19:07 GMT
1 < Location: http://localhost:9090/Produits/50

15:19:07.373 [ForkJoinPool-1-worker-3] INFO  com.intuit.karate - [print] url produit :  http://localhost:9090/Produits/50
15:19:07.374 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - request:
2 > GET http://localhost:9090/Produits/50
2 > Accept-Encoding: gzip,deflate
2 > Connection: Keep-Alive
2 > Host: localhost:9090
2 > User-Agent: Apache-HttpClient/4.5.11 (Java/14)

15:19:07.378 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - response time in milliseconds: 3,33
2 < 200
2 < Content-Type: application/json;charset=UTF-8
2 < Date: Thu, 23 Jul 2020 13:19:07 GMT
2 < Transfer-Encoding: chunked
{"id":50,"nom":"mon Produit","prix":10,"prixAchat":100}


HTML report: (paste into browser to view) | Karate version: 0.9.5
file:/Users/jbcotard/Documents/work/2020_karate/demo-karate/tests-karate/target/surefire-reports/src.test.java.examples.produits.2_recup-produit.html
---------------------------------------------------------

15:19:07.492 [pool-1-thread-1] INFO  com.intuit.karate.Runner - <<pass>> feature 1 of 1: src/test/java/examples/produits/2_recup-produit.feature
---------------------------------------------------------
feature: src/test/java/examples/produits/2_recup-produit.feature
report: target/surefire-reports/src.test.java.examples.produits.2_recup-produit.json
scenarios:  1 | passed:  1 | failed:  0 | time: 0,2998
---------------------------------------------------------
Karate version: 0.9.5
======================================================
elapsed:   0,94 | threads:    1 | thread time: 0,30
features:     1 | ignored:    0 | efficiency: 0,32
scenarios:    1 | passed:     1 | failed: 0
======================================================
----

== Aller plus loin avec la réutilisation de fichier `feature`

.Ecriture du fichier `create-produit-test.feature`
[]
----
@ignore
Feature:

  Scenario: cree le produit test
    * def produit =
      """
      {
        "nom": "test",
        "prix": 100,
        "prixAchat": 120
      }
      """

    Given url 'http://localhost:9090/Produits'
    And request produit
    When method post
    Then status 201

    Given url 'http://localhost:9090/Produits'
    And request produit
    When method post
    Then status 201
----

.Ecriture du fichier `recip-produit-reuse1.feature`
[]
----
Feature: recuperation d'un produit

  Background:
    * def creator = read('create-produit-test.feature')

  Scenario: recupere le produit test apres l'avoir créé
    * def result1 = call creator
    * def locationProduit = $result1.responseHeaders['Location'][0]
    * print 'created produit : ', locationProduit

    Given url locationProduit
    When method get
    Then status 200
----

.Résultat exécution test
[]
----
15:21:01.323 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - request:
1 > POST http://localhost:9090/Produits
1 > Accept-Encoding: gzip,deflate
1 > Connection: Keep-Alive
1 > Content-Length: 41
1 > Content-Type: application/json; charset=UTF-8
1 > Host: localhost:9090
1 > User-Agent: Apache-HttpClient/4.5.11 (Java/14)
{"nom":"test","prix":100,"prixAchat":120}

15:21:01.343 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - response time in milliseconds: 18,63
1 < 201
1 < Content-Length: 0
1 < Date: Thu, 23 Jul 2020 13:21:01 GMT
1 < Location: http://localhost:9090/Produits/51

15:21:01.349 [ForkJoinPool-1-worker-3] INFO  com.intuit.karate - [print] created produit :  http://localhost:9090/Produits/51
15:21:01.350 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - request:
1 > GET http://localhost:9090/Produits/51
1 > Accept-Encoding: gzip,deflate
1 > Connection: Keep-Alive
1 > Host: localhost:9090
1 > User-Agent: Apache-HttpClient/4.5.11 (Java/14)

15:21:01.354 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - response time in milliseconds: 3,14
1 < 200
1 < Content-Type: application/json;charset=UTF-8
1 < Date: Thu, 23 Jul 2020 13:21:01 GMT
1 < Transfer-Encoding: chunked
{"id":51,"nom":"test","prix":100,"prixAchat":120}


HTML report: (paste into browser to view) | Karate version: 0.9.5
file:/Users/jbcotard/Documents/work/2020_karate/demo-karate/tests-karate/target/surefire-reports/src.test.java.examples.produits.3_recup-produit-reuse1.html
---------------------------------------------------------

15:21:01.461 [pool-1-thread-1] INFO  com.intuit.karate.Runner - <<pass>> feature 1 of 1: src/test/java/examples/produits/3_recup-produit-reuse1.feature
---------------------------------------------------------
feature: src/test/java/examples/produits/3_recup-produit-reuse1.feature
report: target/surefire-reports/src.test.java.examples.produits.3_recup-produit-reuse1.json
scenarios:  1 | passed:  1 | failed:  0 | time: 0,3271
---------------------------------------------------------
Karate version: 0.9.5
======================================================
elapsed:   0,96 | threads:    1 | thread time: 0,33
features:     1 | ignored:    0 | efficiency: 0,34
scenarios:    1 | passed:     1 | failed: 0
======================================================
----

== et avec la réutilisation de fichier `feature` paramétrable

.Ecriture du fichier `get-produit.feature`
[]
----
@ignore
Feature:

  Scenario: recupere un produit

    Given url 'http://localhost:9090/'
    And path 'Produits', id
    When method get
    Then status 200

----

.Ecriture du fichier `recep-produit-reuse2.feature`
[]
----
Feature: recuperation d'un produit

  Background:
    * def getter = read('get-produit.feature')

  Scenario: recupere le produit par son id
    * table produits
      | id |
      | 2  |
      | 1  |
      | 3  |
    * def result1 = call getter produits

----

.Résultat exécution test
[]
----
1 > GET http://localhost:9090/Produits/2
1 > Accept-Encoding: gzip,deflate
1 > Connection: Keep-Alive
1 > Host: localhost:9090
1 > User-Agent: Apache-HttpClient/4.5.11 (Java/14)

1 < 200
1 < Content-Type: application/json;charset=UTF-8
1 < Date: Thu, 23 Jul 2020 07:00:10 GMT
1 < Transfer-Encoding: chunked
{"id":2,"nom":"Aspirateur Robot","prix":500,"prixAchat":200}

1 > GET http://localhost:9090/Produits/1
1 > Accept-Encoding: gzip,deflate
1 > Connection: Keep-Alive
1 > Host: localhost:9090
1 > User-Agent: Apache-HttpClient/4.5.11 (Java/14)

1 < 200
1 < Content-Type: application/json;charset=UTF-8
1 < Date: Thu, 23 Jul 2020 07:00:10 GMT
1 < Transfer-Encoding: chunked
{"id":1,"nom":"Ordinateur portable","prix":350,"prixAchat":120}

1 > GET http://localhost:9090/Produits/3
1 > Accept-Encoding: gzip,deflate
1 > Connection: Keep-Alive
1 > Host: localhost:9090
1 > User-Agent: Apache-HttpClient/4.5.11 (Java/14)

1 < 200
1 < Content-Type: application/json;charset=UTF-8
1 < Date: Thu, 23 Jul 2020 07:00:10 GMT
1 < Transfer-Encoding: chunked
{"id":3,"nom":"Table de Ping Pong","prix":750,"prixAchat":400}

----


== Etendre avec des fonctions externes

En complément des fonctions built-in, Karate donne la possibilité de faire appel à des fonctions externes en java ou javascript

[]
----
Feature: Creation d'un produit

  Background:
    * url baseUrl

  Scenario: cree le produit test

    * def getUUID =
      """
      function() {
        return java.util.UUID.randomUUID() + ''
      }
      """

    * def temp = getUUID()
    * print temp

    Given path 'Produits'
    And request {"nom": "test", "prix": 100, "prixAchat": 120}
    When method post
    Then status 201
----

.Résultat exécution test
[]
----
15:23:39.894 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - request:
1 > POST http://localhost:9090/Produits
1 > Accept-Encoding: gzip,deflate
1 > Connection: Keep-Alive
1 > Content-Length: 41
1 > Content-Type: application/json; charset=UTF-8
1 > Host: localhost:9090
1 > User-Agent: Apache-HttpClient/4.5.11 (Java/14)
{"nom":"test","prix":100,"prixAchat":120}

15:23:39.918 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - response time in milliseconds: 22,85
1 < 201
1 < Content-Length: 0
1 < Date: Thu, 23 Jul 2020 13:23:39 GMT
1 < Location: http://localhost:9090/Produits/52


HTML report: (paste into browser to view) | Karate version: 0.9.5
file:/Users/jbcotard/Documents/work/2020_karate/demo-karate/tests-karate/target/surefire-reports/src.test.java.examples.produits.5_autre-produit.html
---------------------------------------------------------

15:23:40.018 [pool-1-thread-1] INFO  com.intuit.karate.Runner - <<pass>> feature 1 of 1: src/test/java/examples/produits/5_autre-produit.feature
---------------------------------------------------------
feature: src/test/java/examples/produits/5_autre-produit.feature
report: target/surefire-reports/src.test.java.examples.produits.5_autre-produit.json
scenarios:  1 | passed:  1 | failed:  0 | time: 0,2811
---------------------------------------------------------
Karate version: 0.9.5
======================================================
elapsed:   0,88 | threads:    1 | thread time: 0,28
features:     1 | ignored:    0 | efficiency: 0,32
scenarios:    1 | passed:     1 | failed: 0
======================================================
----

== Rapport des tests

Karate génére un rapport du résultat de son exécution.

il peut être associé à maven et cucumbert pour générer un rapport plus détaillé.


== Configuration

dans le fichier `karate-config.js`

